### ISSUE TITLE
On initial load, tabs are not present.  

### ISSUE THREAD

**Issue by sethrevelle** [dorontal/ionic-tabs-sidemenu#20]
To replicate change showTabBar to true for 'Tab 1' , and then ionic -serve.  Tabs will not be present on bottom, but are present on page refresh.

**Comment by dorontal** [comment]
Thanks for raising this issue, and apologies I just got to this now.  

What you are describing is a feature, not a big - it is actually intended behavior. If you look in `src/app/tabs/tabs.page.ts` you'll see that the page of the first tab was configured purposely to not show the tab-bar on the bottom, because its `showTabBar` property is set to false:
```typescript
import { Component, ElementRef, ViewChild } from '@angular/core';

import { TabBarService } from  '../tab-bar.service';

const TAB_PAGES: any[] = [
    {
        title: 'Tab 1',
        tab: 'tab1',
        icon: 'search',
        inSidemenu: true,
        inTabBar: false,
        showTabBar: false
    },
    {
        title: 'Tab 2',
        tab: 'tab2',
        icon: 'information-circle',
        inSidemenu: true,
        inTabBar: false,
        showTabBar: true
    },
    {
        title: 'Tab 3',
    ...
```
of course the layout of tabs that's in this app makes no sense at all - it's only set up this way to show the variety of things you can do for each tab page.

**Comment by sethrevelle** [comment]
So I figured out what it is, when navigating to the default route ( tab1 in example app ) the NavigationEnd RouterEvent is navigating to '/' , and then redirecting to '/tabs/tab1' .  

It works handling redirects if you change to 

const execResult: any = /.*\/([^?]+)/.exec((event as NavigationEnd).urlAfterRedirects);

It works with default configuration b/c hideTabBar() is the default in the tab service when url doesn't match regex.
